//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment_Support_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        public int ApplicantId { get; set; }
        public string Title { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string dob { get; set; }
        public string civil_status { get; set; }
    }
}
